export const data = {
  popularMovies: [
    {
      adult: false,
      backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
      genre_ids: [28, 53],
      id: 575264,
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      popularity: 4961.526,
      poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
      release_date: "2023-07-08",
      title: "Mission: Impossible - Dead Reckoning Part One",
      video: false,
      vote_average: 7.7,
      vote_count: 1580,
    },
    {
      adult: false,
      backdrop_path: "/cHNqobjzfLj88lpIYqkZpecwQEC.jpg",
      genre_ids: [28, 53, 80, 18],
      id: 926393,
      original_language: "en",
      original_title: "The Equalizer 3",
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      popularity: 3268.812,
      poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
      release_date: "2023-08-30",
      title: "The Equalizer 3",
      video: false,
      vote_average: 7.3,
      vote_count: 839,
    },
    {
      adult: false,
      backdrop_path: "/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg",
      genre_ids: [27, 9648, 53],
      id: 968051,
      original_language: "en",
      original_title: "The Nun II",
      overview:
        "In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
      popularity: 2992.608,
      poster_path: "/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
      release_date: "2023-09-06",
      title: "The Nun II",
      video: false,
      vote_average: 7,
      vote_count: 966,
    },
    {
      adult: false,
      backdrop_path: "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
      genre_ids: [27, 53],
      id: 1008042,
      original_language: "en",
      original_title: "Talk to Me",
      overview:
        "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
      popularity: 2257.355,
      poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      release_date: "2023-07-26",
      title: "Talk to Me",
      video: false,
      vote_average: 7.2,
      vote_count: 1397,
    },
    {
      adult: false,
      backdrop_path: "/xvzxqKWltnj6qSiWBXRq6ZCdcrw.jpg",
      genre_ids: [53, 18],
      id: 1151534,
      original_language: "es",
      original_title: "Nowhere",
      overview:
        "A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to the child while lost at sea, where she must fight to survive.",
      popularity: 2132.114,
      poster_path: "/uldNFFKNXNvwss0MIZErMSFkBJZ.jpg",
      release_date: "2023-09-29",
      title: "Nowhere",
      video: false,
      vote_average: 7.7,
      vote_count: 611,
    },
    {
      adult: false,
      backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      genre_ids: [28, 18],
      id: 678512,
      original_language: "en",
      original_title: "Sound of Freedom",
      overview:
        "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
      popularity: 2046.775,
      poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
      release_date: "2023-07-03",
      title: "Sound of Freedom",
      video: false,
      vote_average: 8.1,
      vote_count: 891,
    },
    {
      adult: false,
      backdrop_path: "/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg",
      genre_ids: [12, 28, 18],
      id: 980489,
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.",
      popularity: 1701.702,
      poster_path: "/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
      release_date: "2023-08-09",
      title: "Gran Turismo",
      video: false,
      vote_average: 8.1,
      vote_count: 1040,
    },
    {
      adult: false,
      backdrop_path: "/jP3FatCTHc460ZGW57q9ypTdBqu.jpg",
      genre_ids: [53, 878],
      id: 937249,
      original_language: "en",
      original_title: "57 Seconds",
      overview:
        "When a tech blogger lands an interview with a tech guru and stops an attack on him, he finds a mysterious ring that takes him back 57 seconds into the past.",
      popularity: 1667.785,
      poster_path: "/dfS5qHWFuXyZQnwYREwb7N4qU5p.jpg",
      release_date: "2023-09-29",
      title: "57 Seconds",
      video: false,
      vote_average: 5.5,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/fwXeTKmJvlv7kbH8QDmbykGfMeK.jpg",
      genre_ids: [16, 10751, 28, 878],
      id: 893723,
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "A magical meteor crash-lands in Adventure City, gives the PAW Patrol pups superpowers, and transforms them into The Mighty Pups. When the Patrol's archrival Humdinger breaks out of jail and teams up with mad scientist Victoria Vance to steal the powers for themselves, the Mighty Pups must save Adventure City and stop the supervillains before it's too late.",
      popularity: 1562.404,
      poster_path: "/aTvePCU7exLepwg5hWySjwxojQK.jpg",
      release_date: "2023-09-21",
      title: "PAW Patrol: The Mighty Movie",
      video: false,
      vote_average: 7.4,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: "/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg",
      genre_ids: [28, 878, 12],
      id: 565770,
      original_language: "en",
      original_title: "Blue Beetle",
      overview:
        "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.",
      popularity: 1533.325,
      poster_path: "/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
      release_date: "2023-08-16",
      title: "Blue Beetle",
      video: false,
      vote_average: 7.1,
      vote_count: 1285,
    },
    {
      adult: false,
      backdrop_path: "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
      genre_ids: [28, 878, 27],
      id: 615656,
      original_language: "en",
      original_title: "Meg 2: The Trench",
      overview:
        "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
      popularity: 1431.074,
      poster_path: "/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg",
      release_date: "2023-08-02",
      title: "Meg 2: The Trench",
      video: false,
      vote_average: 6.8,
      vote_count: 2239,
    },
    {
      adult: false,
      backdrop_path: "/pWte3Bpf8DHJjzjXP0aCtSewE8y.jpg",
      genre_ids: [28, 80, 53],
      id: 961268,
      original_language: "ko",
      original_title: "발레리나",
      overview:
        "Grieving the loss of a best friend she couldn't protect, an ex-bodyguard sets out to fulfill her dear friend's last wish: sweet revenge.",
      popularity: 1389.816,
      poster_path: "/oE7xtGDqZnr7tFHfwb8oM9iRW6H.jpg",
      release_date: "2023-10-05",
      title: "Ballerina",
      video: false,
      vote_average: 7,
      vote_count: 148,
    },
    {
      adult: false,
      backdrop_path: "/eSsMzJpzAwCa69tm6Wco2il44aJ.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 939335,
      original_language: "en",
      original_title: "Muzzle",
      overview:
        "LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.",
      popularity: 1323.6,
      poster_path: "/qXChf7MFL36BgoLkiB3BzXiwW82.jpg",
      release_date: "2023-09-29",
      title: "Muzzle",
      video: false,
      vote_average: 6.2,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
      genre_ids: [28, 80, 53],
      id: 385687,
      original_language: "en",
      original_title: "Fast X",
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      popularity: 1066.613,
      poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
      release_date: "2023-05-17",
      title: "Fast X",
      video: false,
      vote_average: 7.3,
      vote_count: 3999,
    },
    {
      adult: false,
      backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      popularity: 988.258,
      poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      release_date: "2023-07-19",
      title: "Barbie",
      video: false,
      vote_average: 7.2,
      vote_count: 5398,
    },
    {
      adult: false,
      backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
      genre_ids: [28, 9648, 53, 80],
      id: 762430,
      original_language: "en",
      original_title: "Retribution",
      overview:
        "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
      popularity: 955.039,
      poster_path: "/ljl70pjLIX1hx3bPyCCbxGj6WPr.jpg",
      release_date: "2023-08-23",
      title: "Retribution",
      video: false,
      vote_average: 6.8,
      vote_count: 340,
    },
    {
      adult: false,
      backdrop_path: "/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: "en",
      original_title: "Elemental",
      overview:
        "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
      popularity: 899.15,
      poster_path: "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
      release_date: "2023-06-14",
      title: "Elemental",
      video: false,
      vote_average: 7.7,
      vote_count: 2658,
    },
    {
      adult: false,
      backdrop_path: "/efro4duB7agkA2Xl5LmkD3HeCim.jpg",
      genre_ids: [28, 53, 18],
      id: 818511,
      original_language: "pt",
      original_title: "Carga Máxima",
      overview:
        "When truck racer Roger loses everything, he receives a tempting but dangerous offer: to work as the getaway driver for a gang of thieves.",
      popularity: 879.752,
      poster_path: "/6yx14lSACNJ2zRoYyXqecf3QNgr.jpg",
      release_date: "2023-09-27",
      title: "Overhaul",
      video: false,
      vote_average: 6.9,
      vote_count: 69,
    },
    {
      adult: false,
      backdrop_path: "/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg",
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: "en",
      original_title: "Expend4bles",
      overview:
        "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
      popularity: 839.656,
      poster_path: "/nbrqj9q8WubD3QkYm7n3GhjN7kE.jpg",
      release_date: "2023-09-15",
      title: "Expend4bles",
      video: false,
      vote_average: 6.2,
      vote_count: 186,
    },
    {
      adult: false,
      backdrop_path: "/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
      genre_ids: [10749, 18],
      id: 820525,
      original_language: "en",
      original_title: "After Everything",
      overview:
        "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
      popularity: 835.785,
      poster_path: "/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg",
      release_date: "2023-09-13",
      title: "After Everything",
      video: false,
      vote_average: 6.7,
      vote_count: 299,
    },
  ],
  popularShows: [
    {
      backdrop_path: "/akW2Vt85HZ6qtUjDt1JTtQqB3Jm.jpg",
      first_air_date: "2023-10-02",
      genre_ids: [16],
      id: 233643,
      name: "Secret Mission: Sennyuu Sousakan wa Zettai ni Makenai!",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "しーくれっとみっしょん～潜入捜査官は絶対に負けない！～",
      overview:
        "The story follows two undercover agents Riko Ikazuchi and her junior partner Noma, who are infiltrating an apartment that is also the hideout of a criminal organization. They pretend to be newlyweds. However, when the culprits do not hear noise from them at night, they get suspicious. In order to convince the culprits that they are a married in couple in love, they start to touch and make some noise... Despite feelings of humiliation and pleasure throughout the undercover investigations, Riko endures it and devotes herself to her justice.",
      popularity: 7164.409,
      poster_path: "/ipqu76qqHiVB2vlK2gGZNwF9SwX.jpg",
      vote_average: 6.3,
      vote_count: 5,
    },
    {
      backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
      first_air_date: "1952-12-26",
      genre_ids: [10763],
      id: 94722,
      name: "Tagesschau",
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Tagesschau",
      overview:
        "German daily news program, the oldest still existing program on German television.",
      popularity: 3198.927,
      poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
      vote_average: 7.5,
      vote_count: 149,
    },
    {
      backdrop_path: "/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg",
      first_air_date: "2021-06-09",
      genre_ids: [18, 10765],
      id: 84958,
      name: "Loki",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Loki",
      overview:
        "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
      popularity: 2803.616,
      poster_path: "/voHUmluYmKyleFkTu3lOXQG702u.jpg",
      vote_average: 8.2,
      vote_count: 10279,
    },
    {
      backdrop_path: "/218ZehBKlH8efPRRccmB7bu0oLQ.jpg",
      first_air_date: "2023-09-25",
      genre_ids: [35, 9648, 10766, 18],
      id: 219109,
      name: "Elas por Elas",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Elas por Elas",
      overview: "",
      popularity: 2351.667,
      poster_path: "/hCSH5KvSqShWXhFiXr88wtJXwlO.jpg",
      vote_average: 9,
      vote_count: 2,
    },
    {
      backdrop_path: "/3V3SNPsMa7D6Df9xyepSVbM6m52.jpg",
      first_air_date: "2000-07-18",
      genre_ids: [10764],
      id: 11366,
      name: "Big Brother",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Big Brother",
      overview:
        "A British reality television game show in which a number of contestants live in an isolated house for several weeks, trying to avoid being evicted by the public with the aim of winning a large cash prize at the end of the run.",
      popularity: 2215.191,
      poster_path: "/vT2BBvLHIQysUns1QN9d4gxi002.jpg",
      vote_average: 3.6,
      vote_count: 40,
    },
    {
      backdrop_path: "/hwUQsL1cWt0bmbTxzCompqqvTH9.jpg",
      first_air_date: "2004-01-22",
      genre_ids: [10764],
      id: 82250,
      name: "Gran hermano VIP",
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Gran hermano VIP",
      overview: "",
      popularity: 2103.544,
      poster_path: "/9269PATr0bmEXKjkpR88mzGmNYI.jpg",
      vote_average: 3.7,
      vote_count: 6,
    },
    {
      backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
      first_air_date: "2023-05-08",
      genre_ids: [18, 80, 10766],
      id: 209265,
      name: "Land of Desire",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Terra e Paixão",
      overview:
        "When her husband is killed in a land grabbing attempt, Aline takes charge of cultivating his land and protecting his family. Facing the powerful Antonio La Selva, responsible for the death of her husband and the largest landowner in the region, Aline is determined to keep possession of her land and invest in its production. However, she didn't expect that she would fall in love with Daniel, son of her rival, who is at odds with his rebellious half-brother, Caio, who, in turn, also falls in love with the girl. In the interior of Brazil, Aline will have to fight two battles: the dispute for her lands and for her heart.",
      popularity: 1624.15,
      poster_path: "/6SgKArqMYmqSl5XlHEucGXvotw.jpg",
      vote_average: 6.6,
      vote_count: 120,
    },
    {
      backdrop_path: "/yii7eIlaw1MRMfa7FTA6mW8hBUQ.jpg",
      first_air_date: "2023-08-14",
      genre_ids: [35, 10766],
      id: 213026,
      name: "Fuzuê",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Fuzuê",
      overview: "",
      popularity: 1487.042,
      poster_path: "/zNNFg8z3z7uT817n6M0kHRcYwq1.jpg",
      vote_average: 7.2,
      vote_count: 13,
    },
    {
      backdrop_path: "/l7LRGYJY3NzIGBlpvHpMsNXHbm5.jpg",
      first_air_date: "2023-01-09",
      genre_ids: [10751, 35],
      id: 218145,
      name: "Mama na prenájom",
      origin_country: ["SK"],
      original_language: "sk",
      original_name: "Mama na prenájom",
      overview: "",
      popularity: 1438.423,
      poster_path: "/fH7PP2Rkdlo414IHvZABBHhtoqd.jpg",
      vote_average: 6.3,
      vote_count: 6,
    },
    {
      backdrop_path: "/ScaVfT5IkwVC3Edhmxqyl0GbK0.jpg",
      first_air_date: "2023-09-28",
      genre_ids: [10765, 10759, 18],
      id: 205715,
      name: "Gen V",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Gen V",
      overview:
        "At America's only college for superheroes, gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When the school's dark secrets come to light, they must decide what kind of heroes they want to become.",
      popularity: 1247.696,
      poster_path: "/uuot1N5AgZ7xRCKgm4ZCwOhgIJu.jpg",
      vote_average: 8.1,
      vote_count: 147,
    },
    {
      backdrop_path: "/ohJTnu93hJ0Uonl86Wn3mOSlWXN.jpg",
      first_air_date: "2017-02-06",
      genre_ids: [10751, 35, 18],
      id: 91759,
      name: "Come Home Love: Lo and Behold",
      origin_country: ["HK"],
      original_language: "cn",
      original_name: "愛·回家之開心速遞",
      overview:
        "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
      popularity: 1219.863,
      poster_path: "/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg",
      vote_average: 4.9,
      vote_count: 30,
    },
    {
      backdrop_path: "/ottT2Yt0OfHiHp3PHJTLNVV8JPE.jpg",
      first_air_date: "1992-05-11",
      genre_ids: [18, 10766],
      id: 13945,
      name: "Gute Zeiten, schlechte Zeiten",
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Gute Zeiten, schlechte Zeiten",
      overview:
        "Gute Zeiten, schlechte Zeiten is a long-running German television soap opera, first broadcast on RTL in 1992. The programme concerns the lives of a fictional neighborhood in Germany's capital city Berlin. Over the years the soap opera tends to have an overhaul of young people in their late teens and early twenties; targeting a young viewership.",
      popularity: 1180.11,
      poster_path: "/fNHBzjxsydcAssxXqb5IV2obDdU.jpg",
      vote_average: 7.2,
      vote_count: 19,
    },
    {
      backdrop_path: "/n04w4FxcGE6Sfe0M7zzWohKM3by.jpg",
      first_air_date: "2021-10-12",
      genre_ids: [80, 10765, 18],
      id: 90462,
      name: "Chucky",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Chucky",
      overview:
        "After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town’s hypocrisies and secrets. Meanwhile, the arrival of enemies — and allies — from Chucky’s past threatens to expose the truth behind the killings, as well as the demon doll’s untold origins.",
      popularity: 1176.44,
      poster_path: "/7KbhQpg6OV2o58SoulRbEtK9HYT.jpg",
      vote_average: 7.9,
      vote_count: 3756,
    },
    {
      backdrop_path: "/i4n8ZKmCUaxcGMkPhm12selZiff.jpg",
      first_air_date: "2023-06-12",
      genre_ids: [18, 10766],
      id: 226411,
      name: "Mía es la venganza",
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Mía es la venganza",
      overview: "",
      popularity: 1138.663,
      poster_path: "/wysp5AcY9JpLjje5NunKYw7Mrtc.jpg",
      vote_average: 7.1,
      vote_count: 59,
    },
    {
      backdrop_path: "/2GflJk6Hm1L3FFVWIvnuOskDFGv.jpg",
      first_air_date: "2023-08-28",
      genre_ids: [18, 9648],
      id: 226773,
      name: "Senior High",
      origin_country: ["PH"],
      original_language: "tl",
      original_name: "Senior High",
      overview:
        "A student’s death causes a scandal at the prestigious Northford High. Investigations conclude it was a suicide. The victim’s twin sister thinks otherwise. As she searches for truth, she will unravel secrets that are far more shocking and dangerous.",
      popularity: 1124.298,
      poster_path: "/k285iD6gZIoLsVSczSjc4WIXkdc.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/8cyB9YCbV5CfOyZUUjg2e8U9s1R.jpg",
      first_air_date: "2023-09-20",
      genre_ids: [18],
      id: 235138,
      name: "Against The Light",
      origin_country: ["CN"],
      original_language: "zh",
      original_name: "流光之下",
      overview: "",
      popularity: 1122.289,
      poster_path: "/7LWNDuzouwBsAQ45wGxbjforxRZ.jpg",
      vote_average: 7,
      vote_count: 3,
    },
    {
      backdrop_path: "/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg",
      first_air_date: "2005-01-03",
      genre_ids: [35, 10767],
      id: 14981,
      name: "The Late Late Show with Craig Ferguson",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Late Show with Craig Ferguson",
      overview:
        "The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n\nSince becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.",
      popularity: 1113.857,
      poster_path: "/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg",
      vote_average: 7,
      vote_count: 78,
    },
    {
      backdrop_path: "/rj3jBAZwPiOgkwAy1205MAgLahj.jpg",
      first_air_date: "2018-08-27",
      genre_ids: [10766],
      id: 81329,
      name: "Chronicles of the Sun",
      origin_country: ["FR"],
      original_language: "fr",
      original_name: "Un si grand soleil",
      overview: "",
      popularity: 1101.124,
      poster_path: "/t6jVlbPMtZOJoAOfeoR4yQmnjXM.jpg",
      vote_average: 7.5,
      vote_count: 49,
    },
    {
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      first_air_date: "2015-09-08",
      genre_ids: [35, 10767],
      id: 63770,
      name: "The Late Show with Stephen Colbert",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.",
      popularity: 1083.963,
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      vote_average: 6.5,
      vote_count: 206,
    },
    {
      backdrop_path: "/1stoC4UstDtmST8x8VATtf08KfL.jpg",
      first_air_date: "2005-10-13",
      genre_ids: [10766],
      id: 206559,
      name: "Binnelanders",
      origin_country: ["ZA"],
      original_language: "af",
      original_name: "Binnelanders",
      overview:
        "A South African Afrikaans soap opera. It is set in and around the fictional private hospital, Binneland Kliniek, in Pretoria, and the storyline follows the trials, trauma and tribulations of the staff and patients of the hospital.",
      popularity: 1078.729,
      poster_path: "/v9nGSRx5lFz6KEgfmgHJMSgaARC.jpg",
      vote_average: 4.6,
      vote_count: 13,
    },
  ],
  top_ratedMovies: [
    {
      adult: false,
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 122.492,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.7,
      vote_count: 18764,
    },
    {
      adult: false,
      backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 106.113,
      poster_path: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.7,
      vote_count: 24736,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 64.56,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.6,
      vote_count: 11345,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 60.305,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 14654,
    },
    {
      adult: false,
      backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 26.92,
      poster_path: "/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.6,
      vote_count: 4260,
    },
    {
      adult: false,
      backdrop_path: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 84.154,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.5,
      vote_count: 14963,
    },
    {
      adult: false,
      backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 48.958,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.5,
      vote_count: 7699,
    },
    {
      adult: false,
      backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 73.688,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.5,
      vote_count: 16501,
    },
    {
      adult: false,
      backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
      genre_ids: [10749, 16, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 90.884,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.5,
      vote_count: 10353,
    },
    {
      adult: false,
      backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 99.381,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.5,
      vote_count: 30724,
    },
    {
      adult: false,
      backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 87.849,
      poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.5,
      vote_count: 16007,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 73.596,
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.5,
      vote_count: 25986,
    },
    {
      adult: false,
      backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 88.971,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.5,
      vote_count: 25498,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 102.428,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-01",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.5,
      vote_count: 22416,
    },
    {
      adult: false,
      backdrop_path: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 68.587,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-23",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.5,
      vote_count: 7785,
    },
    {
      adult: false,
      backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 58.029,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.5,
      vote_count: 11780,
    },
    {
      adult: false,
      backdrop_path: "/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: "ja",
      original_title: "火垂るの墓",
      overview:
        "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
      popularity: 0.6,
      poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
      release_date: "1988-04-16",
      title: "Grave of the Fireflies",
      video: false,
      vote_average: 8.5,
      vote_count: 4887,
    },
    {
      adult: false,
      backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
      genre_ids: [35, 18],
      id: 637,
      original_language: "it",
      original_title: "La vita è bella",
      overview:
        "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
      popularity: 48.674,
      poster_path: "/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg",
      release_date: "1997-12-20",
      title: "Life Is Beautiful",
      video: false,
      vote_average: 8.5,
      vote_count: 12266,
    },
    {
      adult: false,
      backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 35.899,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3248,
    },
    {
      adult: false,
      backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
      genre_ids: [18, 10749],
      id: 11216,
      original_language: "it",
      original_title: "Nuovo Cinema Paradiso",
      overview:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
      popularity: 28.803,
      poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
      release_date: "1988-11-17",
      title: "Cinema Paradiso",
      video: false,
      vote_average: 8.5,
      vote_count: 3978,
    },
  ],
  top_ratedShows: [
    {
      backdrop_path: "/7BzmK4MWc0cj4hCxwWURt6TS6UR.jpg",
      first_air_date: "2023-08-31",
      genre_ids: [16, 10765, 10759, 35],
      id: 131378,
      name: "Adventure Time: Fionna & Cake",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Adventure Time: Fionna & Cake",
      overview:
        "Fionna and Cake – with the help of the former Ice King, Simon Petrikov - embark on a multiverse-hopping adventure and journey of self-discovery. All the while a powerful new antagonist determined to track them down and erase them from existence, lurks in the shadows.",
      popularity: 214.198,
      poster_path: "/fi1b6U1kp73xheECzqwzMn8u3mX.jpg",
      vote_average: 9.3,
      vote_count: 112,
    },
    {
      backdrop_path: "/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
      first_air_date: "2008-01-20",
      genre_ids: [18, 80],
      id: 1396,
      name: "Breaking Bad",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Bad",
      overview:
        "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      popularity: 300.732,
      poster_path: "/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg",
      vote_average: 8.9,
      vote_count: 12459,
    },
    {
      backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
      first_air_date: "2021-11-06",
      genre_ids: [16, 18, 10765, 10759],
      id: 94605,
      name: "Arcane",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Arcane",
      overview:
        "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
      popularity: 72.044,
      poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
      vote_average: 8.7,
      vote_count: 3354,
    },
    {
      backdrop_path: "/4Mt7WHox67uJ1yErwTBFcV8KWgG.jpg",
      first_air_date: "1999-10-20",
      genre_ids: [10759, 35, 16],
      id: 37854,
      name: "One Piece",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "ワンピース",
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      popularity: 150.512,
      poster_path: "/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
      vote_average: 8.7,
      vote_count: 4082,
    },
    {
      backdrop_path: "/1zVcwxZLNCBMCLN2g6hLu17IGfO.jpg",
      first_air_date: "2013-12-02",
      genre_ids: [16, 35, 10765, 10759],
      id: 60625,
      name: "Rick and Morty",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Rick and Morty",
      overview:
        "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
      popularity: 790.82,
      poster_path: "/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
      vote_average: 8.7,
      vote_count: 8626,
    },
    {
      backdrop_path: "/A6tMQAo6t6eRFCPhsrShmxZLqFB.jpg",
      first_air_date: "2009-04-05",
      genre_ids: [10759, 16, 10765],
      id: 31911,
      name: "Fullmetal Alchemist: Brotherhood",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "鋼の錬金術師 FULLMETAL ALCHEMIST",
      overview:
        "Edward and Alphonse Elric's reckless disregard for alchemy's fun­damental laws ripped half of Ed's limbs from his body and left Al's soul clinging to a cold suit of armor. To restore what was lost, the brothers scour a war-torn land for the Philosopher's Sto­ne, a fabled relic which grants the ability to perform alchemy in impossible ways.\n\nThe Elrics are not alone in their search; the corrupt State Military is also eager to harness the artifact's power. So too are the strange Homunculi and their shadowy creator. The mythical gem lures exotic alchemists from distant kingdoms, scarring some deeply enough to inspire murder. As the Elrics find their course altered by these enemies and allies, their purpose remains unchanged – and their bond unbreakable.",
      popularity: 121.343,
      poster_path: "/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg",
      vote_average: 8.7,
      vote_count: 1756,
    },
    {
      backdrop_path: "/70YdbMELM4b8x8VXjlubymb2bQ0.jpg",
      first_air_date: "2017-03-19",
      genre_ids: [18, 10751],
      id: 70785,
      name: "Anne with an E",
      origin_country: ["CA"],
      original_language: "en",
      original_name: "Anne with an E",
      overview:
        "A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.",
      popularity: 78.78,
      poster_path: "/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg",
      vote_average: 8.7,
      vote_count: 4387,
    },
    {
      backdrop_path: "/kU98MbVVgi72wzceyrEbClZmMFe.jpg",
      first_air_date: "2005-02-21",
      genre_ids: [16, 10759, 10765],
      id: 246,
      name: "Avatar: The Last Airbender",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Avatar: The Last Airbender",
      overview:
        "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
      popularity: 61.909,
      poster_path: "/cHFZA8Tlv03nKTGXhLOYOLtqoSm.jpg",
      vote_average: 8.7,
      vote_count: 3505,
    },
    {
      backdrop_path: "/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg",
      first_air_date: "2019-04-06",
      genre_ids: [16, 10759, 10765],
      id: 85937,
      name: "Demon Slayer: Kimetsu no Yaiba",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "鬼滅の刃",
      overview:
        "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
      popularity: 92.798,
      poster_path: "/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
      vote_average: 8.7,
      vote_count: 5638,
    },
    {
      backdrop_path: "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
      first_air_date: "2021-03-25",
      genre_ids: [16, 10765, 10759, 18],
      id: 95557,
      name: "Invincible",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Invincible",
      overview:
        "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
      popularity: 154.643,
      poster_path: "/lxVS24ZhG3WQf3IMbkFIg6olT6A.jpg",
      vote_average: 8.7,
      vote_count: 3730,
    },
    {
      backdrop_path: "/jsXKG9uppnPrhqFNhImllyCfLhl.jpg",
      first_air_date: "2016-04-03",
      genre_ids: [10759, 16],
      id: 65930,
      name: "My Hero Academia",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "僕のヒーローアカデミア",
      overview:
        "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
      popularity: 46.022,
      poster_path: "/ivOLM47yJt90P19RH1NvJrAJz9F.jpg",
      vote_average: 8.7,
      vote_count: 4518,
    },
    {
      backdrop_path: "/hMjvf1xGcCbbobFuM2iYR9Tj0Yr.jpg",
      first_air_date: "2022-04-22",
      genre_ids: [18],
      id: 124834,
      name: "Heartstopper",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Heartstopper",
      overview:
        "Teens Charlie and Nick discover their unlikely friendship might be something more as they navigate school and young love in this coming-of-age series.",
      popularity: 77.99,
      poster_path: "/p0AtD0ivSlHq2MHY6JFgyhNqAQY.jpg",
      vote_average: 8.7,
      vote_count: 1054,
    },
    {
      backdrop_path: "/uoA7xBzCt3XXqL5fMmB8pmYgABJ.jpg",
      first_air_date: "2016-12-02",
      genre_ids: [18, 10765, 35],
      id: 67915,
      name: "Goblin",
      origin_country: ["KR"],
      original_language: "ko",
      original_name: "쓸쓸하고 찬란하神-도깨비",
      overview:
        "In his quest for a bride to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper and a sprightly student with a tragic past.",
      popularity: 65.591,
      poster_path: "/sPkxHNw5BFvuCFGWw825TS7n6X3.jpg",
      vote_average: 8.7,
      vote_count: 2548,
    },
    {
      backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
      first_air_date: "2023-01-15",
      genre_ids: [18],
      id: 100088,
      name: "The Last of Us",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Last of Us",
      overview:
        "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
      popularity: 178.682,
      poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
      vote_average: 8.7,
      vote_count: 4103,
    },
    {
      backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
      first_air_date: "2013-04-07",
      genre_ids: [10765, 16, 10759],
      id: 1429,
      name: "Attack on Titan",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "進撃の巨人",
      overview:
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
      popularity: 68.782,
      poster_path: "/8C5gYahMFmzHKGNID8QrG5t25WU.jpg",
      vote_average: 8.7,
      vote_count: 5517,
    },
    {
      backdrop_path: "/cHyY5z4txdVyGtYMvBJhCqCcJso.jpg",
      first_air_date: "2020-01-10",
      genre_ids: [16, 10765, 18, 10759, 35],
      id: 92685,
      name: "The Owl House",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Owl House",
      overview:
        "An animated fantasy-comedy series that follows Luz, a self-assured teenage girl who accidentally stumbles upon a portal to a magical world where she befriends a rebellious witch, Eda, and an adorably tiny warrior, King. Despite not having magical abilities, Luz pursues her dream of becoming a witch by serving as Eda's apprentice at the Owl House and ultimately finds a new family in an unlikely setting.",
      popularity: 171.468,
      poster_path: "/zhdy3PcNVE15wj1wrxn45ARZBnx.jpg",
      vote_average: 8.7,
      vote_count: 1384,
    },
    {
      backdrop_path: "/2vbE9ajftJ7dkqUAyxDS0WFILx8.jpg",
      first_air_date: "2010-09-06",
      genre_ids: [16, 35],
      id: 31132,
      name: "Regular Show",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Regular Show",
      overview:
        "Two bored groundskeepers, Mordecai (a six-foot-tall blue jay) and Rigby (a hyperactive raccoon) are best friends who spend their days trying to entertain themselves by any means necessary, much to the displeasure of their boss. Their everyday pursuits often lead to things spiraling out of control and into the surreal.",
      popularity: 241.046,
      poster_path: "/mS5SLxMYcKfUxA0utBSR5MOAWWr.jpg",
      vote_average: 8.7,
      vote_count: 1787,
    },
    {
      backdrop_path: "/900tHlUYUkp7Ol04XFSoAaEIXcT.jpg",
      first_air_date: "2019-05-06",
      genre_ids: [18],
      id: 87108,
      name: "Chernobyl",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Chernobyl",
      overview:
        "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
      popularity: 67.809,
      poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
      vote_average: 8.7,
      vote_count: 5398,
    },
    {
      backdrop_path: "/5jtc5va1gDiRi9pjnGqgCN1W0hF.jpg",
      first_air_date: "2006-07-09",
      genre_ids: [16, 35, 18],
      id: 42821,
      name: "Welcome to the N.H.K.",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "NHKにようこそ!",
      overview:
        "Sato's life – or what's left of it – is a paranoid mess of conspiracy theories and social anxieties. He's terrified of the outside world; his apartment is overflowing with the remnants of cheap take-out food; and his retinas have been permanently scarred by a steady diet of internet porn. But maybe it's not all his fault. After all, the nefarious N.H.K. is out there, and they’re determined to turn society's fringe-dwellers into a brainwashed lot of jobless, hopeless, futureless recluses.\n\nEnter Misaki – a mysterious girl-next-door type who is Sato's last chance to beat-down his inner demons and venture out into the light of day. She's ready to help him overcome his crippling phobias, but Sato would rather cower in his existential foxhole and pretend to work on the demo for his virtual sex game.\n\nHe’s afraid to face the world. She's strangely desperate to fix a total stranger. Maybe together they can be normal.",
      popularity: 26.89,
      poster_path: "/hIsRcWso57zxD2MWBSqze5G4NDS.jpg",
      vote_average: 8.6,
      vote_count: 104,
    },
    {
      backdrop_path: "/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
      first_air_date: "2015-02-08",
      genre_ids: [80, 18],
      id: 60059,
      name: "Better Call Saul",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Better Call Saul",
      overview:
        'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
      popularity: 153.277,
      poster_path: "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
      vote_average: 8.6,
      vote_count: 4384,
    },
  ],
};
