export const PopularMoviesRes = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
      genre_ids: [28, 53],
      id: 575264,
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      popularity: 3691.876,
      poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
      release_date: "2023-07-08",
      title: "Mission: Impossible - Dead Reckoning Part One",
      video: false,
      vote_average: 7.8,
      vote_count: 1506,
    },
    {
      adult: false,
      backdrop_path: "/cHNqobjzfLj88lpIYqkZpecwQEC.jpg",
      genre_ids: [28, 53, 80, 18],
      id: 926393,
      original_language: "en",
      original_title: "The Equalizer 3",
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      popularity: 2767.64,
      poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
      release_date: "2023-08-30",
      title: "The Equalizer 3",
      video: false,
      vote_average: 7.4,
      vote_count: 783,
    },
    {
      adult: false,
      backdrop_path: "/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg",
      genre_ids: [27, 9648, 53],
      id: 968051,
      original_language: "en",
      original_title: "The Nun II",
      overview:
        "In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
      popularity: 2386.129,
      poster_path: "/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
      release_date: "2023-09-06",
      title: "The Nun II",
      video: false,
      vote_average: 7,
      vote_count: 920,
    },
    {
      adult: false,
      backdrop_path: "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
      genre_ids: [27, 53],
      id: 1008042,
      original_language: "en",
      original_title: "Talk to Me",
      overview:
        "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
      popularity: 2140.444,
      poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      release_date: "2023-07-26",
      title: "Talk to Me",
      video: false,
      vote_average: 7.2,
      vote_count: 1345,
    },
    {
      adult: false,
      backdrop_path: "/xvzxqKWltnj6qSiWBXRq6ZCdcrw.jpg",
      genre_ids: [53, 18],
      id: 1151534,
      original_language: "es",
      original_title: "Nowhere",
      overview:
        "A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to the child while lost at sea, where she must fight to survive.",
      popularity: 1779.423,
      poster_path: "/uldNFFKNXNvwss0MIZErMSFkBJZ.jpg",
      release_date: "2023-09-29",
      title: "Nowhere",
      video: false,
      vote_average: 7.7,
      vote_count: 578,
    },
    {
      adult: false,
      backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      genre_ids: [28, 18],
      id: 678512,
      original_language: "en",
      original_title: "Sound of Freedom",
      overview:
        "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
      popularity: 1714.928,
      poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
      release_date: "2023-07-03",
      title: "Sound of Freedom",
      video: false,
      vote_average: 8.1,
      vote_count: 859,
    },
    {
      adult: false,
      backdrop_path: "/fwXeTKmJvlv7kbH8QDmbykGfMeK.jpg",
      genre_ids: [16, 10751, 28, 878],
      id: 893723,
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "A magical meteor crash-lands in Adventure City, gives the PAW Patrol pups superpowers, and transforms them into The Mighty Pups. When the Patrol's archrival Humdinger breaks out of jail and teams up with mad scientist Victoria Vance to steal the powers for themselves, the Mighty Pups must save Adventure City and stop the supervillains before it's too late.",
      popularity: 1492.743,
      poster_path: "/aTvePCU7exLepwg5hWySjwxojQK.jpg",
      release_date: "2023-09-21",
      title: "PAW Patrol: The Mighty Movie",
      video: false,
      vote_average: 7.7,
      vote_count: 41,
    },
    {
      adult: false,
      backdrop_path: "/jP3FatCTHc460ZGW57q9ypTdBqu.jpg",
      genre_ids: [53, 878],
      id: 937249,
      original_language: "en",
      original_title: "57 Seconds",
      overview:
        "When a tech blogger lands an interview with a tech guru and stops an attack on him, he finds a mysterious ring that takes him back 57 seconds into the past.",
      popularity: 1421.819,
      poster_path: "/dfS5qHWFuXyZQnwYREwb7N4qU5p.jpg",
      release_date: "2023-09-29",
      title: "57 Seconds",
      video: false,
      vote_average: 5.5,
      vote_count: 69,
    },
    {
      adult: false,
      backdrop_path: "/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg",
      genre_ids: [12, 28, 18],
      id: 980489,
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.",
      popularity: 1374.1,
      poster_path: "/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
      release_date: "2023-08-09",
      title: "Gran Turismo",
      video: false,
      vote_average: 8.1,
      vote_count: 1009,
    },
    {
      adult: false,
      backdrop_path: "/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg",
      genre_ids: [28, 878, 12],
      id: 565770,
      original_language: "en",
      original_title: "Blue Beetle",
      overview:
        "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.",
      popularity: 1240.699,
      poster_path: "/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
      release_date: "2023-08-16",
      title: "Blue Beetle",
      video: false,
      vote_average: 7.1,
      vote_count: 1263,
    },
    {
      adult: false,
      backdrop_path: "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
      genre_ids: [28, 878, 27],
      id: 615656,
      original_language: "en",
      original_title: "Meg 2: The Trench",
      overview:
        "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
      popularity: 1121.092,
      poster_path: "/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg",
      release_date: "2023-08-02",
      title: "Meg 2: The Trench",
      video: false,
      vote_average: 6.8,
      vote_count: 2222,
    },
    {
      adult: false,
      backdrop_path: "/eSsMzJpzAwCa69tm6Wco2il44aJ.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 939335,
      original_language: "en",
      original_title: "Muzzle",
      overview:
        "LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.",
      popularity: 1053.989,
      poster_path: "/qXChf7MFL36BgoLkiB3BzXiwW82.jpg",
      release_date: "2023-09-29",
      title: "Muzzle",
      video: false,
      vote_average: 6,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: "/pWte3Bpf8DHJjzjXP0aCtSewE8y.jpg",
      genre_ids: [28, 80, 53],
      id: 961268,
      original_language: "ko",
      original_title: "발레리나",
      overview:
        "Grieving the loss of a best friend she couldn't protect, an ex-bodyguard sets out to fulfill her dear friend's last wish: sweet revenge.",
      popularity: 992.726,
      poster_path: "/oE7xtGDqZnr7tFHfwb8oM9iRW6H.jpg",
      release_date: "2023-10-05",
      title: "Ballerina",
      video: false,
      vote_average: 7.1,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
      genre_ids: [28, 80, 53],
      id: 385687,
      original_language: "en",
      original_title: "Fast X",
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      popularity: 902.234,
      poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
      release_date: "2023-05-17",
      title: "Fast X",
      video: false,
      vote_average: 7.3,
      vote_count: 3988,
    },
    {
      adult: false,
      backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      popularity: 849.591,
      poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      release_date: "2023-07-19",
      title: "Barbie",
      video: false,
      vote_average: 7.2,
      vote_count: 5374,
    },
    {
      adult: false,
      backdrop_path: "/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
      genre_ids: [10749, 18],
      id: 820525,
      original_language: "en",
      original_title: "After Everything",
      overview:
        "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
      popularity: 809.616,
      poster_path: "/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg",
      release_date: "2023-09-13",
      title: "After Everything",
      video: false,
      vote_average: 6.8,
      vote_count: 285,
    },
    {
      adult: false,
      backdrop_path: "/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: "en",
      original_title: "Elemental",
      overview:
        "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
      popularity: 787.286,
      poster_path: "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
      release_date: "2023-06-14",
      title: "Elemental",
      video: false,
      vote_average: 7.7,
      vote_count: 2634,
    },
    {
      adult: false,
      backdrop_path: "/efro4duB7agkA2Xl5LmkD3HeCim.jpg",
      genre_ids: [28, 53, 18],
      id: 818511,
      original_language: "pt",
      original_title: "Carga Máxima",
      overview:
        "When truck racer Roger loses everything, he receives a tempting but dangerous offer: to work as the getaway driver for a gang of thieves.",
      popularity: 730.337,
      poster_path: "/6yx14lSACNJ2zRoYyXqecf3QNgr.jpg",
      release_date: "2023-09-27",
      title: "Overhaul",
      video: false,
      vote_average: 6.9,
      vote_count: 61,
    },
    {
      adult: false,
      backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
      genre_ids: [28, 9648, 53, 80],
      id: 762430,
      original_language: "en",
      original_title: "Retribution",
      overview:
        "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
      popularity: 684.182,
      poster_path: "/ljl70pjLIX1hx3bPyCCbxGj6WPr.jpg",
      release_date: "2023-08-23",
      title: "Retribution",
      video: false,
      vote_average: 6.8,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
      genre_ids: [27, 53],
      id: 951491,
      original_language: "en",
      original_title: "Saw X",
      overview:
        "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
      popularity: 678.999,
      poster_path: "/b16RAVwj2QN6RAs752UJNzQ9Of0.jpg",
      release_date: "2023-09-26",
      title: "Saw X",
      video: false,
      vote_average: 7.3,
      vote_count: 139,
    },
  ],
  total_pages: 40508,
  total_results: 810143,
};
